add_library(recording_ctl_commands STATIC recording_ctl.cc recording_control_client.cc)
target_include_directories(recording_ctl_commands PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(recording_ctl_commands PRIVATE contracts diagnostic_cli runtime time_util)

add_executable(recording-ctl main.cc)
target_link_libraries(recording-ctl PRIVATE recording_ctl_commands)
