set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(JETSON_SYSROOT "$ENV{JETSON_SYSROOT}" CACHE PATH
    "Root filesystem copied from the target Jetson")
if(NOT JETSON_SYSROOT OR NOT IS_DIRECTORY "${JETSON_SYSROOT}")
    message(FATAL_ERROR
        "JETSON_SYSROOT must point to a Jetson root filesystem")
endif()

set(CMAKE_SYSROOT "${JETSON_SYSROOT}")
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH
    "${JETSON_SYSROOT}"
    "${JETSON_SYSROOT}/usr"
    "${JETSON_SYSROOT}/usr/local/cuda"
)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${JETSON_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${JETSON_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${JETSON_SYSROOT}/usr/lib/pkgconfig:${JETSON_SYSROOT}/usr/share/pkgconfig")

set(COCKPIT_TARGET_ARCH arm64 CACHE STRING "" FORCE)
set(COCKPIT_TARGET_SYSTEM Linux CACHE STRING "" FORCE)
