add_subdirectory(diagnostics)
add_subdirectory(can-simulator)
add_subdirectory(cockpit-ctl)
add_subdirectory(recording-ctl)
add_subdirectory(safe-ota)
add_subdirectory(audio-probe)
add_subdirectory(camera-ctl)
add_subdirectory(camera-probe)
add_subdirectory(camera-preview-probe)
add_subdirectory(voice-ctl)
add_subdirectory(topic)
