add_subdirectory(core)
add_subdirectory(modules)
add_subdirectory(drivers)
add_subdirectory(proto)
add_subdirectory(navigator)
add_subdirectory(library)

add_subdirectory(processes/vehicle)
add_subdirectory(processes/gateway)
add_subdirectory(processes/cloud)
add_subdirectory(processes/audio)
add_subdirectory(processes/camera)
add_subdirectory(processes/recording)
add_subdirectory(processes/interaction)

if(BUILD_COCKPIT_UI)
    add_subdirectory(apps/cockpit-ui)
endif()
